class ExportEngine {
  exportToPDF(meeting) {
    const { jsPDF } = window.jspdf || {};
    if (!jsPDF) {
      this.downloadText(this.generateText(meeting), meeting.title + '.txt');
      return;
    }
    
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text(meeting.title.toUpperCase(), 105, 20, { align: 'center' });
    
    doc.setFontSize(11);
    let y = 35;
    doc.text(`Date: ${new Date(meeting.date).toLocaleString()}`, 20, y); y += 7;
    doc.text(`Duration: ${this.formatDuration(meeting.duration)}`, 20, y); y += 7;
    doc.text(`Type: ${meeting.meetingType}`, 20, y); y += 7;
    doc.text(`Languages: ${meeting.languages.join(', ')}`, 20, y); y += 10;
    
    if (meeting.summary) {
      doc.setFontSize(16);
      doc.text('EXECUTIVE SUMMARY', 20, y); y += 10;
      doc.setFontSize(11);
      const summaryLines = doc.splitTextToSize(meeting.summary.executiveSummary, 170);
      doc.text(summaryLines, 20, y); y += summaryLines.length * 5 + 10;
      
      if (meeting.summary.decisions.length) {
        doc.setFontSize(16);
        doc.text('DECISIONS', 20, y); y += 10;
        doc.setFontSize(11);
        meeting.summary.decisions.forEach(d => {
          const lines = doc.splitTextToSize(`${d.confidence === 'High' ? '✓' : '⚠️'} ${d.title}: ${d.description}`, 170);
          doc.text(lines, 20, y); y += lines.length * 5 + 3;
        });
        y += 5;
      }
    }
    
    if (meeting.transcript) {
      doc.addPage();
      doc.setFontSize(16);
      doc.text('TRANSCRIPT', 20, 20);
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(meeting.transcript, 170);
      doc.text(lines, 20, 35);
    }
    
    doc.save(`${meeting.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
  }

  exportToMarkdown(meeting) {
    const md = this.generateMarkdown(meeting);
    this.downloadText(md, meeting.title.replace(/[^a-z0-9]/gi, '_') + '.md');
  }

  exportToText(meeting) {
    const text = this.generateText(meeting);
    this.downloadText(text, meeting.title.replace(/[^a-z0-9]/gi, '_') + '.txt');
  }

  generateMarkdown(meeting) {
    let md = `# ${meeting.title}\n\n`;
    md += `**Date:** ${new Date(meeting.date).toLocaleString()}\n`;
    md += `**Duration:** ${this.formatDuration(meeting.duration)}\n`;
    md += `**Type:** ${meeting.meetingType}\n\n`;
    
    if (meeting.summary) {
      md += `## Executive Summary\n\n${meeting.summary.executiveSummary}\n\n`;
      
      if (meeting.summary.decisions.length) {
        md += `## Decisions\n\n`;
        meeting.summary.decisions.forEach(d => {
          md += `### ${d.confidence === 'High' ? '✅' : '⚠️'} ${d.title}\n`;
          md += `- **Description:** ${d.description}\n`;
          md += `- **Confidence:** ${d.confidence}\n`;
          md += `- **Evidence:** [${this.formatTime(d.evidence.timestamp)}]\n\n`;
        });
      }
      
      if (meeting.summary.actionItems.length) {
        md += `## Action Plan\n\n| Task | PIC | Deadline | Status |\n|------|-----|----------|--------|\n`;
        meeting.summary.actionItems.forEach(item => {
          md += `| ${item.task} | ${item.pic} | ${item.deadline || 'TBD'} | ${item.status} |\n`;
        });
        md += `\n`;
      }
    }
    
    if (meeting.transcript) {
      md += `## Transcript\n\n\`\`\`\n${meeting.transcript}\n\`\`\`\n`;
    }
    
    md += `\n---\n*Generated by Meeting Assistant Pro | Local Processing Only*\n`;
    return md;
  }

  generateText(meeting) {
    let text = `MEETING MINUTES\n================\n\n`;
    text += `Title: ${meeting.title}\n`;
    text += `Date: ${new Date(meeting.date).toLocaleString()}\n`;
    text += `Duration: ${this.formatDuration(meeting.duration)}\n\n`;
    
    if (meeting.summary) {
      text += `EXECUTIVE SUMMARY\n-----------------\n${meeting.summary.executiveSummary}\n\n`;
      
      if (meeting.summary.decisions.length) {
        text += `DECISIONS\n---------\n`;
        meeting.summary.decisions.forEach(d => {
          text += `[${d.confidence}] ${d.title}\n    ${d.description}\n    Evidence: ${this.formatTime(d.evidence.timestamp)}\n\n`;
        });
      }
      
      if (meeting.summary.actionItems.length) {
        text += `ACTION PLAN\n-----------\n`;
        meeting.summary.actionItems.forEach(item => {
          text += `[${item.status}] ${item.task}\n    PIC: ${item.pic} | Deadline: ${item.deadline || 'TBD'}\n\n`;
        });
      }
    }
    
    if (meeting.transcript) {
      text += `\nTRANSCRIPT\n----------\n${meeting.transcript}\n`;
    }
    
    text += `\n--------------------\nGenerated by Meeting Assistant Pro | Local Processing Only\n`;
    return text;
  }

  downloadText(content, filename) {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  formatDuration(ms) {
    const totalSeconds = Math.floor(ms / 1000);
    const h = Math.floor(totalSeconds / 3600);
    const m = Math.floor((totalSeconds % 3600) / 60);
    const s = totalSeconds % 60;
    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;
  }

  formatTime(ms) {
    const totalSeconds = Math.floor(ms / 1000);
    const h = Math.floor(totalSeconds / 3600);
    const m = Math.floor((totalSeconds % 3600) / 60);
    const s = totalSeconds % 60;
    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;
  }
}
